package app.eduroam.geteduroam.ui.theme

import androidx.compose.ui.graphics.Color

//Generated via https://material-foundation.github.io/material-theme-builder/#/custom

val md_theme_light_primary = Color(0xFF00658d)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFc3e7ff)
val md_theme_light_onPrimaryContainer = Color(0xFF001e2d)
val md_theme_light_secondary = Color(0xFF006c46)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFF8df7c2)
val md_theme_light_onSecondaryContainer = Color(0xFF002112)
val md_theme_light_tertiary = Color(0xFF954a03)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFffdbc4)
val md_theme_light_onTertiaryContainer = Color(0xFF311300)
val md_theme_light_error = Color(0xFFB3261E)
val md_theme_light_errorContainer = Color(0xFFF9DEDC)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410E0B)
val md_theme_light_background = Color(0xFFfbfcfe)
val md_theme_light_onBackground = Color(0xFF191c1e)
val md_theme_light_surface = Color(0xFFfbfcfe)
val md_theme_light_onSurface = Color(0xFF191c1e)
val md_theme_light_surfaceVariant = Color(0xFFE7E0EC)
val md_theme_light_onSurfaceVariant = Color(0xFF49454F)
val md_theme_light_outline = Color(0xFF79747E)
val md_theme_light_inverseOnSurface = Color(0xFFf0f1f3)
val md_theme_light_inverseSurface = Color(0xFF2e3133)
val md_theme_light_inversePrimary = Color(0xFF7cd0ff)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF7cd0ff)
val md_theme_dark_onPrimary = Color(0xFF00344b)
val md_theme_dark_primaryContainer = Color(0xFF004c6b)
val md_theme_dark_onPrimaryContainer = Color(0xFFc3e7ff)
val md_theme_dark_secondary = Color(0xFF70daa7)
val md_theme_dark_onSecondary = Color(0xFF003822)
val md_theme_dark_secondaryContainer = Color(0xFF005234)
val md_theme_dark_onSecondaryContainer = Color(0xFF8df7c2)
val md_theme_dark_tertiary = Color(0xFFffb683)
val md_theme_dark_onTertiary = Color(0xFF512400)
val md_theme_dark_tertiaryContainer = Color(0xFF733600)
val md_theme_dark_onTertiaryContainer = Color(0xFFffdbc4)
val md_theme_dark_error = Color(0xFFF2B8B5)
val md_theme_dark_errorContainer = Color(0xFF8C1D18)
val md_theme_dark_onError = Color(0xFF601410)
val md_theme_dark_onErrorContainer = Color(0xFFF9DEDC)
val md_theme_dark_background = Color(0xFF191c1e)
val md_theme_dark_onBackground = Color(0xFFe1e3e5)
val md_theme_dark_surface = Color(0xFF191c1e)
val md_theme_dark_onSurface = Color(0xFFe1e3e5)
val md_theme_dark_surfaceVariant = Color(0xFF49454F)
val md_theme_dark_onSurfaceVariant = Color(0xFFCAC4D0)
val md_theme_dark_outline = Color(0xFF938F99)
val md_theme_dark_inverseOnSurface = Color(0xFF191c1e)
val md_theme_dark_inverseSurface = Color(0xFFe1e3e5)
val md_theme_dark_inversePrimary = Color(0xFF00658d)
val md_theme_dark_shadow = Color(0xFF000000)


val seed = Color(0xFF6750A4)
val error = Color(0xFFB3261E)
